name: Frontend

on:
  push:
    paths:
    - "frontend/**"
    - ".github/workflows/frontend.yaml"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Create prod auth config
      working-directory: frontend
      run: |
        echo '${{ secrets.PROD_FE_AUTH_CONFIG }}' > auth_config.json
    - name: yarn install, build, and unittest
      working-directory: frontend
      run: |
        yarn install
        yarn build
        yarn test:unit
    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions@0.1.1
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GC_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GC_SERVICE_ACCOUNT_KEY }}
    - name: Deploy to AppEngine
      working-directory: frontend
      run: |
        gcloud config set project ${{ secrets.GC_PROJECT_ID }}
        gcloud app deploy
      


